export const zhHeader: string;
export const headerInner: string;
export const logo: string;
export const linkLogo: string;
export const zhContent: string;
export const dailyItem: string;
export const imgWrap: string;
export const shortGraph: string;
export const itemLink: string;
